version: "3"
services:
  mongo:
    image: mongo:3.6.3-jessie
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  product-service:
    build: ./product-service/
    ports:
      - 8082:8082
    environment:
      MICROSERVICE_REVIEW_HOST: "http://review-service"
      MICROSERVICE_REVIEW_PORT: "8083"
    depends_on:
      - review-service
  review-service:
    build: ./review-service/
    environment: 
      MONGO_HOST: "mongo"
      MONGO_URI: "mongodb://mongo/test"
    ports:
      - 8083:8083
    depends_on:
      - mongo
  
volumes: 
  mongo: 
