version: "3"
services:
  auth-service:
    build: ./auth-service/
    ports:
      - 8080:8081
    environment:
      MONGO_URI: 'mongodb://mongo/test'
    links:
      - mongo           
  product-service:
    build: ./product-service/
    environment: 
      - "MONGO_URI:mongodb://mongo/test"
    ports:
      - 8080:8082
    links:
      - mongo
  review-service:
    build: ./review-service/
    environment: 
      - "MONGO_URI:mongodb://mongo/test"
    ports:
      - 8080:8083
    links:
      - mongo
  mongo:
    image: mongo:3.6.3-jessie
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
volumes: 
  mongo: 
