version: "3"
services:
  mongo:
    image: mongo:3.6.3-jessie
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/redis
  product-service:
    build: ./product-service/
    ports:
      - 8082:8082
    environment:
      MICROSERVICE_REVIEW_HOST: "http://localhost"
      MICROSERVICE_REVIEW_PORT: "8083"
    depends_on:
      - review-service
      - redis
  review-service:
    build: ./review-service/
    environment: 
      MONGO_HOST: "mongo"
      MONGO_URI: "mongodb://mongo/test"
    ports:
      - 8083:8083
    depends_on:
      - mongo
      - redis
  
volumes: 
  mongo: 
  redis:
