version: "3"
services:
  mongo:
    image: mongo:3.6.3-jessie
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  product-service:
    build: ./product-service/
    ports:
      - 8082:8080
  review-service:
    build: ./review-service/
    environment: 
      MONGO_HOST: "mongo"
      MONGO_URI: "mongodb://mongo/test"
    ports:
      - 8083:8080
    depends_on:
      - mongo
  
volumes: 
  mongo: 
