FROM openjdk:11.0.2-jdk-oracle

# Add a volume pointing to /tmp
# VOLUME /tmp

COPY pom.xml /opt/product-service/build/
COPY mvnw /opt/product-service/build/
ADD .mvn /opt/product-service/build/.mvn/
ADD src /opt/product-service/build/src/

WORKDIR /opt/product-service/build/

RUN ./mvnw clean package

FROM openjdk:11.0.2-jdk-oracle
# Maven build is mandatory before copying jar file : $ ./mvnw clean package

WORKDIR /opt/product-service/

COPY --from=0 /opt/product-service/build/target/product-service-0.0.1-SNAPSHOT.jar product-service.jar

# Make port 8080 available to the world outside this container
EXPOSE 8082

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","product-service.jar"]
